#!/usr/bin/env node
import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const configFileName = 'marple.config.js';

function detectFramework(packageJson) {
  const deps = { ...packageJson.dependencies, ...packageJson.devDependencies };
  if (deps?.next) return 'Next.js';
  if (deps?.express) return 'Express';
  return 'Node.js';
}

function configTemplate() {
  return `// Marple configuration generated by npx marple init
export default {
  storage: 'sqlite',
  sqlitePath: './marple.sqlite',
  retention: {
    keepRawEventsDays: 30,
    keepRollupsDays: 365,
    autoRollup: true
  },
  dashboardPath: '/marple',
};
`;
}

async function runInit() {
  const cwd = process.cwd();
  const packageJsonPath = path.join(cwd, 'package.json');

  let projectType = 'Node.js';
  try {
    const packageJsonRaw = await readFile(packageJsonPath, 'utf8');
    const packageJson = JSON.parse(packageJsonRaw);
    projectType = detectFramework(packageJson);
  } catch (error) {
  }

  const configPath = path.join(cwd, configFileName);
  const exists = await readFile(configPath).then(() => true).catch(() => false);
  if (exists) { 
    console.error('marple.config.js already exists. Delete it first.'); 
    process.exit(1); 
  }

  const content = configTemplate();
  await writeFile(configPath, content, 'utf8');

  console.log('✔✔ Created', configFileName);
  console.log('Detected framework:', projectType);
  console.log('Add Marple to your server configuration and protect /marple with authentication.');
}

async function run() {
  const [command] = process.argv.slice(2);

  if (!command || command === 'help' || command === '--help') {
    console.log('Marple CLI');
    console.log('Usage: npx marple <command>');
    console.log('Commands:');
    console.log('  init    Create a marple.config.js boilerplate file');
    return;
  }

  if (command === 'init') {
    await runInit();
    return;
  }

  console.error('Unknown command:', command);
  process.exit(1);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
